/*
 *     The Certora Prover
 *     Copyright (C) 2025  Certora Ltd.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, version 3 of the License.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package move

import datastructures.stdcollections.*
import java.math.BigInteger
import java.nio.file.*
import kotlin.io.path.*
import kotlinx.serialization.json.*

/**
    Parses the Sui package summaries found in the package summary directory generated by `sui move summary`.

    Currently the only thing we get from here is the address aliases.
 */
class SuiPackageSummaries(val packageSummaryPath: Path) {
    /*
        Address aliases are stored in `address_mapping.json` as a dictionary of the form:
        ```
            {
                "std": "0x0000000000000000000000000000000000000000000000000000000000000001",
                "sui": "0x0000000000000000000000000000000000000000000000000000000000000002",
                "test": "0x0000000000000000000000000000000000000000000000000000000000000000"
            }
        ```
     */
    val addressAliases = Json.decodeFromString<Map<String, String>>(
        Files.readString(packageSummaryPath / "address_mapping.json")
    ).mapValues { (alias, address) ->
        @Suppress("ForbiddenMethodCall")
        check(address.startsWith("0x")) { "Expecting hexadecimal address for alias '$alias', got: $address" }
        BigInteger(address.substring(2), 16)
    }
}
