// GENERATED by generate.py -- edit that instead.
//
// Exercises the EIP-8024 instructions DUPN (0xe6), SWAPN (0xe7) and EXCHANGE
// (0xe8), none of which any released compiler emits. Each `verbatim` blob
// builds its own deep stack, applies one instruction, and unwinds back to a
// single value, because the operands of these instructions sit deeper than the
// 16 slots solc's stack allocator can marshal as `verbatim` inputs.
object "Eip8024" {
    code {
        datacopy(0, dataoffset("Runtime"), datasize("Runtime"))
        return(0, datasize("Runtime"))
    }
    object "Runtime" {
        code {
            if lt(calldatasize(), 4) { revert(0, 0) }
            // The selector reaches the switch through one DUPN, one SWAPN and one
            // EXCHANGE, so DispatchAnalysis has to model all three to recover any
            // method path at all.
            // PUSH1 0x01 PUSH1 0x02 PUSH1 0x03 PUSH1 0x04 PUSH1 0x05 PUSH1 0x06 PUSH1 0x07 PUSH1 0x08 PUSH1 0x09 PUSH1 0x0a PUSH1 0x0b PUSH1 0x0c PUSH1 0x0d PUSH1 0x0e PUSH1 0x0f PUSH1 0x10 PUSH1 0x11 DUPN 18 SWAPN 17 EXCHANGE 1 17 POP SWAP1 POP x17
            switch verbatim_1i_1o(hex"600160026003600460056006600760086009600a600b600c600d600e600f60106011e681e780e84f5090509050905090509050905090509050905090509050905090509050905090509050", shr(224, calldataload(0)))
            // dupn(uint256) -> x
            // DUPN 18 over 17 distinct fillers, so an off-by-one in the immediate decoding surfaces as a constant rather than as x.
            // PUSH1 0x01 PUSH1 0x02 PUSH1 0x03 PUSH1 0x04 PUSH1 0x05 PUSH1 0x06 PUSH1 0x07 PUSH1 0x08 PUSH1 0x09 PUSH1 0x0a PUSH1 0x0b PUSH1 0x0c PUSH1 0x0d PUSH1 0x0e PUSH1 0x0f PUSH1 0x10 PUSH1 0x11 DUPN 18 SWAP1 POP x18
            case 0xb8a83dc4 {
                ret(verbatim_1i_1o(hex"600160026003600460056006600760086009600a600b600c600d600e600f60106011e681905090509050905090509050905090509050905090509050905090509050905090509050", arg(0)))
            }
            // dupnStopImmediate(uint256) -> x
            // DUPN 145 encodes to the immediate 0x00, which is STOP if the byte following the opcode is not skipped.
            // PUSH0 x144 DUPN 145 SWAP1 POP x145
            case 0x0057d859 {
                ret(verbatim_1i_1o(hex"5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5fe6009050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050", arg(0)))
            }
            // dupnSelfdestructImmediate(uint256) -> x
            // DUPN 144 encodes to the immediate 0xff, which is SELFDESTRUCT if the byte following the opcode is not skipped.
            // PUSH0 x143 DUPN 144 SWAP1 POP x144
            case 0x8ce8a663 {
                ret(verbatim_1i_1o(hex"5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5fe6ff905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050905090509050", arg(0)))
            }
            // swapn(uint256,uint256) -> y
            // SWAPN 17 lifts the 18th item to the top. Its immediate is 0x80, which is DUP1 if the immediate is mistaken for an opcode.
            // PUSH1 0x01 PUSH1 0x02 PUSH1 0x03 PUSH1 0x04 PUSH1 0x05 PUSH1 0x06 PUSH1 0x07 PUSH1 0x08 PUSH1 0x09 PUSH1 0x0a PUSH1 0x0b PUSH1 0x0c PUSH1 0x0d PUSH1 0x0e PUSH1 0x0f PUSH1 0x10 SWAPN 17 SWAP1 POP x17
            case 0x38920a9c {
                ret(verbatim_2i_1o(hex"600160026003600460056006600760086009600a600b600c600d600e600f6010e78090509050905090509050905090509050905090509050905090509050905090509050", arg(0), arg(1)))
            }
            // exchange(uint256,uint256) -> y
            // EXCHANGE 3 4 has m <= 16, exercising the first branch of the pair encoding.
            // PUSH1 0x01 PUSH1 0x02 PUSH1 0x03 EXCHANGE 3 4 POP x3 SWAP1 POP
            case 0xd4b7eac3 {
                ret(verbatim_2i_1o(hex"600160026003e8ac5050509050", arg(0), arg(1)))
            }
            // exchangeDeep(uint256,uint256) -> y
            // EXCHANGE 1 20 has m > 16, exercising the second branch of the pair encoding.
            // PUSH1 0x01 PUSH1 0x02 PUSH1 0x03 PUSH1 0x04 PUSH1 0x05 PUSH1 0x06 PUSH1 0x07 PUSH1 0x08 PUSH1 0x09 PUSH1 0x0a PUSH1 0x0b PUSH1 0x0c PUSH1 0x0d PUSH1 0x0e PUSH1 0x0f PUSH1 0x10 PUSH1 0x11 PUSH1 0x12 PUSH1 0x13 EXCHANGE 1 20 POP SWAP1 POP x19
            case 0xf09d973f {
                ret(verbatim_2i_1o(hex"600160026003600460056006600760086009600a600b600c600d600e600f6010601160126013e81f509050905090509050905090509050905090509050905090509050905090509050905090509050", arg(0), arg(1)))
            }
            // dupnJumpdestImmediate() -> halts
            // 0x5b is not a legal immediate: EIP-8024 reserves it so that jumpdest analysis is unaffected, and requires an exceptional halt here.
            // DUPN <invalid immediate 0x5b>
            case 0x65e2e46f {
                verbatim_0i_0o(hex"e65b")
                ret(0)
            }
            default { revert(0, 0) }

            function arg(i) -> v { v := calldataload(add(4, mul(32, i))) }
            function ret(v) { mstore(0, v) return(0, 32) }
        }
    }
}
