/*
 *     The Certora Prover
 *     Copyright (C) 2025  Certora Ltd.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, version 3 of the License.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package verifier.equivalence.tracing

import tac.MetaKey
import utils.*
import vc.data.TACSymbol
import vc.data.TransformableVarEntityWithSupport

/**
 * Debugging artifact left to help debug instrumentation states.
 * [which] is the id of the read, and [desc] is a (sort of) human readable description of what the long read is.
 * [records] are generated by the various [InstrumentationMixin] implementations, and are basic key-value maps. However,
 * the presence of this record prevents the folding/simplification of the involved variables.
 */
data class ReadSiteInstrumentationRecord(
    val which: Int,
    val desc : String,
    val records: List<InstrumentationRecord>
) : TransformableVarEntityWithSupport<ReadSiteInstrumentationRecord> {
    override fun transformSymbols(f: (TACSymbol.Var) -> TACSymbol.Var): ReadSiteInstrumentationRecord {
        return ReadSiteInstrumentationRecord(
            which = which,
            desc = desc,
            records = records.map { rec ->
                rec.transformSymbols(f)
            }
        )
    }

    override val support: Set<TACSymbol.Var>
        get() = records.flatMapToSet { rec -> rec.support }

    companion object {
        val META_KEY = MetaKey<ReadSiteInstrumentationRecord>("buffer.tracing.instrumentation.info")
    }
}
